### ISSUE TITLE
Gem Broken: Google doesn't accept form encoded input.

### ISSUE THREAD

**Issue by bramski** [zigotto/googl#29]
```
irb(main):005:0> Googl.shorten("http://www.microsoft.com", "127.0.0.1", Utilities::Link.google_api_key).short_url
Googl::Error: {"error"=>{"errors"=>[{"domain"=>"global", "reason"=>"parseError", "message"=>"This API does not support parsing form-encoded input."}], "code"=>400, "message"=>"This API does not support parsing form-encoded input."}}
    from /app/vendor/bundle/ruby/2.3.0/gems/googl-0.7.1/lib/googl/shorten.rb:29:in `initialize'
    from /app/vendor/bundle/ruby/2.3.0/gems/googl-0.7.1/lib/googl.rb:29:in `new'
    from /app/vendor/bundle/ruby/2.3.0/gems/googl-0.7.1/lib/googl.rb:29:in `shorten'
    from (irb):5
```

**Comment by digitalextremist** [comment]
Moved to this gem for the above reason: https://rubygems.org/gems/google_url_shortener

https://github.com/joshnesbitt/google_url_shortener/

**Comment by st0012** [comment]
I think this issue is related to the `httparty` gem it uses. I have the same issue when using version `0.15.6`, and solved it by downgrade it to `0.14.0`.

**Comment by march-3-1994** [comment]
[]()
